---
title: "Untitled"
author: "Rahma Fairuz Rania"
date: "10/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(scales)
library(glue)
library(plotly)
library(dplyr)
library(tidyr)
library(lubridate)
library(shiny)
library(shinydashboard)
```

```{r}
anime <- read.csv('tidy_anime.csv', stringsAsFactors = FALSE)

anime <- anime[, -c(3,4,5,13,24,25,28)]

anime$animeID <- as.character(anime$animeID)
anime$type <- as.factor(anime$type)
anime$genre <- as.factor(anime$genre)

anime$start_date <- ymd(anime$start_date)
anime$end_date <- ymd(anime$end_date)

anime <- anime %>% 
  separate(premiered, c("prem_season", "prem_year")) %>% 
    separate(broadcast, c("broad_day", "at", "Time", "tz"), sep = " " ) %>% 
      select(-c(at,tz))

anime$rating <- as.factor(anime$rating)
anime$prem_season <- as.factor(anime$prem_season)
anime$broad_day <- as.factor(anime$broad_day)
anime$prem_year <- as.numeric(anime$prem_year)

anime$prem_Season <- ifelse(as.numeric(format.Date(anime$start_date, "%m")) %in% c(12,1,2), "Winter",
                            ifelse(as.numeric(format.Date(anime$start_date, "%m")) %in% c(3,4,5), "Spring",
                                   ifelse(as.numeric(format.Date(anime$start_date, "%m")) %in% c(6,7,8), "Summer",
                                          ifelse(as.numeric(format.Date(anime$start_date, "%m")) %in% c(9,10,11), "Fall",
                                                 no = NA )))) 

unique_anime <- data.frame(anime %>% distinct(animeID, .keep_all = TRUE))
head(unique_anime)
```




```{r}
anime_trend <- unique_anime %>% 
      filter(prem_year < 2019) %>% 
      filter(!is.na(prem_year)) %>%
      group_by(year = prem_year) %>% 
      summarise(freq = n())%>% 
      ungroup() %>% 
      mutate(label = glue("Year: {year}
                      Total: {freq} anime"))


plot1 <- ggplot(anime_trend, mapping = aes(x = year, y = freq)) +
      geom_line() +
      geom_point(col = "navy",aes(text = label)) +
      labs(title = 'Anime Trend perYear',
           x = "Premiered Year",
           y = NULL) +
      theme_minimal()
    
ggplotly(plot1, tooltip = "text")
```



```{r}
anime_genre <- unique_anime %>% 
      filter(genre == 'Action') %>% 
      group_by(name) %>% 
      summarise(avg_scored_by = mean(scored_by)) %>% 
      ungroup() %>% 
      arrange(desc(avg_scored_by))
anime_genre <- head(anime_genre, 15) %>% 
      mutate(label = glue("{name}
                      Average Rating: {comma(avg_scored_by)}"))
```

```{r}
plot2 <- ggplot(anime_genre, aes(x = avg_scored_by, y = reorder(name, avg_scored_by), text = label)) +
      geom_col(aes(fill = avg_scored_by)) +
      labs(title = paste("Top 15 Anime"),
           subtitle = "According to Scored by User",
           x = "Average Score",
           y = NULL) +
      scale_fill_gradient(low = "yellow", high= "red") +
      scale_x_continuous(labels = comma) +
      theme_minimal() +
      theme(legend.position = "none") +
      scale_x_continuous(labels = label_number(suffix = " M", scale = 1e-6))
    
ggplotly(plot2, tooltip = "text")
```

```{r}
sea_broad <- unique_anime %>% 
  filter(!(is.na(broad_day))) %>% 
  filter(!(broad_day == "Unknown")) %>% 
  filter(!(broad_day == "Not")) %>% 
  group_by(prem_season) %>% 
  summarise( freq = n()) %>% 
  ungroup() %>% mutate(label = glue("{prem_season}
                            Total: {freq}"))
sea_broad <- drop_na(sea_broad)
sea_broad <- head(sea_broad)

plot3 <- ggplot(sea_broad,aes(y = reorder(prem_season, freq), x = freq) ,text = label) +
  geom_col() + theme_minimal() + theme(legend.position = "none") + labs(title = paste("Top 15 Anime"),
           x = "Total Broadcast",
           y = NULL) 
ggplotly(plot3, label = 'text')

```







```{r}
anime_broad <- unique_anime %>% 
  filter(!(is.na(broad_day))) %>% 
  filter(!(broad_day == "Unknown")) %>% 
  filter(!(broad_day == "Not")) %>% 
      group_by(broad_day, studio) %>% 
      summarise(mean_rate = n()) %>%  
      ungroup() %>% mutate(label = glue("{studio}
                           Popularity: {comma(mean_rate)}"))
anime_broad <- head(anime_broad, 5)


plot3 <- ggplot(anime_broad, aes(x = studio, y = ordered(broad_day, mean_rate), text = label)) +
      geom_col(aes(fill = studio)) +
      labs(title = paste("Top 15 Popular Studio"),
           subtitle = "According to Scored by User",
           x = "Average Popularity",
           y = NULL) 
    
plot3
ggplotly(plot3, label = 'text')
```
```{r}
unique_anime
```


```{r}
sea_broad <- unique_anime %>% 
      filter(season = input$season)
      group_by(genre) %>% 
      summarise( freq = n()) %>% 
      ungroup() %>% mutate(label = glue("Genre {genre}
                            Total: {freq}"))
    sea_broad <- drop_na(sea_broad)
    sea_broad <- head(sea_broad)
    
    plot3 <- ggplot(sea_broad,aes(y = reorder(genre, freq), x = freq, text = label)) +
      geom_col(aes(fill = freq)) + theme_minimal() + theme(legend.position = "none") + labs(title = paste("Anime Broadcast Season"),
                                                                            x = "Total Broadcast",
                                                                            y = NULL) + scale_x_continuous(labels = comma) +
      theme_minimal() +
      theme(legend.position = 'none') + theme(plot.title = element_text(face = "bold", hjust = 0.5),
                                              plot.subtitle = element_text(hjust = 0.5))
    ggplotly(plot3, label = 'text')
```

